### PR TITLE
Added alias support for queries and mutations

### PR DESCRIPTION
**Pull request by PaulProject**

### CODE REVIEW

**Comment by VerachadW** [comment]
Hey @PaulProject. Thanks for the PR. Could you please check the errors from CI Build and add some example for usage as well?

**Comment by PaulProject** [comment]
I have a problem with run JUnit tests. I installed Spek plugin for AS 3.2.1, run tests and see error:
```
WARNING: TestEngine with ID 'spek' failed to discover tests
org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: me.lazmaid.kraph.test.DataEntrySpek
```

**Comment by VerachadW** [comment]
@PaulProject Sorry for the delay. Quite busy here. I will check by today. Could you show me your version of Spek plugin? Did you have the latest version?

**Comment by VerachadW** [comment]
I just changed the target branch to develop. Try to update and rerun again

**Comment by VerachadW** [comment]
@PaulProject Hey, I think we are good to merge. Could you also write HOW-TO in README.md as well?

**Comment by PaulProject** [comment]
Yes of course, give me some time

**Comment by PaulProject** [comment]
I have some conflicts. Do I need resolve it?

**Comment by PaulProject** [comment]
I resolve the conflicts, do I need to push the change?

**Comment by VerachadW** [comment]
@PaulProject Yes, please

**Comment by PaulProject** [comment]
Hi @VerachadW, what do you think about code coverage? Do I need to fix the checks?

**Comment by VerachadW** [comment]
@PaulProject Yes, please.

**Comment by VerachadW** [comment]
@PaulProject How was the coverage? Could you be able to fix it? It wants to have 1 version release before next year. If possible, I want your changes as well.

**Comment by PaulProject** [comment]
Hi, I don’t have any time for fix it. I have a problem with run the tests (I wrote about it) and I can’t check the code coverage. If you can help me, we do it.

**Pull request merged**
