### PR TITLE
Support Kotlin 1.3.71

### PR DESCRIPTION
**Pull request by AlexeySoshin**
This PR updates version of:
* Kotlin 1.1.51 -> 1.3.71
* Gradle 3.4.1 -> 6.0.1
* Travis OpenJDK 8 -> 11
* Jacoco 0.7~ -> 0.8.5

### CODE REVIEW

**Comment by AlexeySoshin** [comment]
@VerachadW WDYT?

**Comment by VerachadW** [comment]
Hi @AlexeySoshin , it good for me. Just wondering if you want to bump to 1.3.72 instead?

**Comment by AlexeySoshin** [comment]
> Hi @AlexeySoshin , it good for me. Just wondering if you want to bump to 1.3.72 instead?

That's a good idea.
Done!

**Comment by VerachadW** [comment]
Not sure why the travis CI status is not updated here, but since it passed. I will merge now.

**Pull request merged**
